import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Playground - smacon.dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>
          play.smacon.dev
        </h2>

        <p className={styles.description}>
          playground of{' '}
          <Link href="https://www.smacon.dev" className="underline">www.smacon.dev</Link>
        </p>

        <div className={styles.grid}>
          <Link href="/solidity">
            <a className={styles.card}>
              <h2>Solidity &rarr;</h2>
            </a>
          </Link>

          <a
            href="/motoko" className={styles.card}
          >
            <h2>Motoko &rarr;</h2>
          </a>
          
          <a
            href="/rust" className={styles.card}
          >
            <h2>Rust &rarr;</h2>
          </a>

          <a
            href="/rust" className={styles.card}
          >
            <h2>smacon.dev &rarr;</h2>
          </a>
        </div>


      </main>

      <footer className={styles.footer}>
        <a
          href="https://www.smacon.dev"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by smacon.dev
        </a>
      </footer>
    </div>
  )
}
